// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe7h6juNn5hQSVGqBYjqyYMoQd6V0dfsA',
    appId: '1:557103334938:web:bbf7e7873a6bfa66c3b3a3',
    messagingSenderId: '557103334938',
    projectId: 'eetacgo',
    authDomain: 'eetacgo.firebaseapp.com',
    storageBucket: 'eetacgo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACWhZlWh9xcg2EUdIUn-KF6175ACCe7LQ',
    appId: '1:557103334938:android:3d30fa74130ba514c3b3a3',
    messagingSenderId: '557103334938',
    projectId: 'eetacgo',
    storageBucket: 'eetacgo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhJ-BPOhlcSRFIzIjIuReYYZb-7BJf_88',
    appId: '1:557103334938:ios:8c5078feadab86e3c3b3a3',
    messagingSenderId: '557103334938',
    projectId: 'eetacgo',
    storageBucket: 'eetacgo.appspot.com',
    iosClientId: '557103334938-uu7ke7tesl1g3e00fujietnhbl5fo2rl.apps.googleusercontent.com',
    iosBundleId: 'com.example.eaFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhJ-BPOhlcSRFIzIjIuReYYZb-7BJf_88',
    appId: '1:557103334938:ios:8c5078feadab86e3c3b3a3',
    messagingSenderId: '557103334938',
    projectId: 'eetacgo',
    storageBucket: 'eetacgo.appspot.com',
    iosClientId: '557103334938-uu7ke7tesl1g3e00fujietnhbl5fo2rl.apps.googleusercontent.com',
    iosBundleId: 'com.example.eaFrontend',
  );
}
